# Generated by Django 2.2.1 on 2019-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_remove_estudio_usuario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio_usuario',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
