# Generated by Django 2.2.1 on 2019-10-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_auto_20191006_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio_usuario',
            name='leido',
        ),
        migrations.AlterField(
            model_name='estudio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia'),
        ),
    ]
