# Generated by Django 2.2.4 on 2019-10-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_auto_20191007_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia'),
        ),
    ]
