# Generated by Django 2.2.1 on 2019-09-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('semestre', models.IntegerField(blank=True)),
                ('anio', models.IntegerField(blank=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Materia')),
            ],
        ),
    ]
