# Generated by Django 2.2.1 on 2019-09-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivo',
            new_name='Ejercicio',
        ),
    ]
