# Generated by Django 2.2.1 on 2019-09-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('preguntas', '0002_auto_20190912_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuelto', models.BooleanField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario')),
            ],
        ),
    ]
