# Generated by Django 2.2.1 on 2019-10-01 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preguntas', '0004_auto_20190918_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio'),
        ),
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ejercicio_usuario',
            unique_together={('ejercicio', 'usuario')},
        ),
    ]
