# Generated by Django 2.2.1 on 2019-10-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_auto_20191001_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio'),
        ),
    ]
