# Generated by Django 2.2.4 on 2019-10-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20191001_2325'),
        ('preguntas', '0005_auto_20190925_1458'),
    ]

    operations = [
    ]
