# Generated by Django 2.2.4 on 2019-10-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_merge_20191003_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia'),
        ),
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio'),
        ),
    ]
