# Generated by Django 2.2.1 on 2019-10-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_auto_20191003_1812'),
        ('preguntas', '0010_auto_20191003_1753'),
    ]

    operations = [
    ]
