# Generated by Django 2.2.1 on 2019-10-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0012_auto_20191006_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia'),
        ),
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio'),
        ),
    ]
