# Generated by Django 2.2.1 on 2019-10-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0016_auto_20191007_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(default='Nombre_Archivo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia'),
        ),
        migrations.AlterField(
            model_name='ejercicio_usuario',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio'),
        ),
    ]
