# Generated by Django 2.2.1 on 2019-10-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_auto_20191001_2110'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
