# Generated by Django 2.2.1 on 2019-10-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='certamen', max_length=255)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('semestre', models.IntegerField(blank=True)),
                ('anio', models.IntegerField(blank=True)),
                ('nombre', models.CharField(max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.materia')),
            ],
        ),
        migrations.CreateModel(
            name='certamen_pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.certamen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='ejercicio_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuelto', models.BooleanField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ejercicio', 'usuario')},
            },
        ),
    ]
